apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
     project: roboshop
     component: frontend
     environment: dev
     annotations:
       imageregistry: "https:hub.docker.com"
       jenjinsURL: "https://jenkins.joindevops.com/build/joindevops"

    spec:
      containers:
      - name: nginx
        image: nginx     