apiVersion: v1
kind: Service
metadata:
    name: nginx
  spec:
    selector:
    #lables are used as selectors
    project: roboshop1
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 

  